# Generated by Django 5.2.5 on 2025-08-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storename', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=100)),
                ('created_date', models.CharField(max_length=200)),
            ],
        ),
    ]
