# Generated by Django 5.2.6 on 2025-09-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprofile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
