# Generated by Django 5.2.5 on 2025-08-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_basecredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
