# Generated by Django 5.2.5 on 2025-09-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_storeprofile_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportprofile',
            name='columns',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='reportprofile',
            name='sub_section',
            field=models.TextField(max_length=10),
        ),
    ]
