# Generated by Django 5.2.5 on 2025-08-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_storeprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprofile',
            name='slug',
            field=models.SlugField(),
        ),
    ]
