# Generated by Django 5.2.6 on 2025-09-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_reportprofile_columns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportprofile',
            name='selected_columns',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='reportprofile',
            name='sub_section',
            field=models.CharField(max_length=100),
        ),
    ]
