# Generated by Django 5.2.6 on 2025-09-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_reportprofile_selected_columns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportprofile',
            name='updated_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
