# Generated by Django 5.2.6 on 2025-09-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_reportprofile_updated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportprofile',
            name='pivot_table',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportprofile',
            name='tally_table',
            field=models.BooleanField(default=False),
        ),
    ]
