# Generated by Django 5.2.5 on 2025-09-12 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_storeprofile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportProfile',
            fields=[
                ('basecredential_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.basecredential')),
                ('columns', models.CharField(max_length=1000)),
                ('main_section', models.CharField(max_length=20)),
                ('sub_section', models.TextField(max_length=100)),
            ],
            bases=('dashboard.basecredential',),
        ),
    ]
