# Generated by Django 5.2.6 on 2025-09-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_reportprofile_pivot_table_reportprofile_tally_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportprofile',
            name='pivot_table',
        ),
        migrations.AddField(
            model_name='reportprofile',
            name='pivot_columns',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
