# Generated by Django 5.2.5 on 2025-09-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_reportprofile_pivot_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportprofile',
            name='tally_table',
        ),
        migrations.AddField(
            model_name='reportprofile',
            name='tally_columns',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
