# Generated by Django 5.1.6 on 2025-09-13 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyApiCredential',
            fields=[
                ('basecredential_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.basecredential')),
                ('storename', models.CharField(max_length=10)),
                ('access_token', models.CharField(max_length=200)),
            ],
            bases=('dashboard.basecredential',),
        ),
    ]
