# Generated by Django 5.2.5 on 2025-08-12 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=200)),
                ('client_secret', models.CharField(max_length=200)),
                ('refresh_token', models.CharField(max_length=200)),
                ('access_token', models.CharField(blank=True, max_length=200, null=True)),
                ('access_token_refreshing_time', models.DateTimeField(auto_now_add=True)),
                ('storeprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.storeprofile')),
            ],
        ),
    ]
