# Generated by Django 5.2.5 on 2025-08-13 10:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_rename_amazonstore_spapicredentials'),
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpapiCredentials',
            new_name='SpapiCredential',
        ),
    ]
