# Generated by Django 5.2.5 on 2025-08-13 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_rename_spapicredentials_spapicredential'),
        ('dashboard', '0002_basecredential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spapicredential',
            name='id',
        ),
        migrations.RemoveField(
            model_name='spapicredential',
            name='store',
        ),
        migrations.RemoveField(
            model_name='spapicredential',
            name='user',
        ),
        migrations.AddField(
            model_name='spapicredential',
            name='basecredential_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.basecredential'),
            preserve_default=False,
        ),
    ]
