# Generated by Django 5.2.5 on 2025-08-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_remove_spapicredential_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spapicredential',
            name='access_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='spapicredential',
            name='client_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='spapicredential',
            name='client_secret',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='spapicredential',
            name='refresh_token',
            field=models.CharField(max_length=500),
        ),
    ]
