# Generated by Django 5.1.6 on 2025-08-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0005_alter_spapicredential_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spapicredential',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='spapicredential',
            name='access_token_refreshing_time',
        ),
    ]
